basePath: /api/v1
definitions:
  models.Error:
    properties:
      código:
        type: integer
      mensagem:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Api de Teste com Golang + Gin Web(https://github.com/gin-gonic/gin)
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Experimento com Golang - MicroServices
  version: "1.0"
paths:
  /test/hello:
    get:
      description: Api de Teste com Golang + Gin Web(https://github.com/gin-gonic/gin)
      produces:
      - application/json
      responses:
        "200": {}
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Checa se o serviço está funcinando
      tags:
      - test
swagger: "2.0"
